name: Node.js Package

on:
  push:
    tags:
      - [0-9]+.[0-9]+.[0-9]+

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.5
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm test
